#include "check_tamper_i.h"
#include <furi_hal_nfc.h>
#include <dolphin/dolphin.h>

/* generated by fbt from .png files in images folder */
//#include <check_tamper_icons.h>

bool check_tamper_custom_event_callback(void* context, uint32_t event) {
    furi_assert(context);
    CheckTamper* check_tamper = context;
    return scene_manager_handle_custom_event(check_tamper->scene_manager, event);
}

bool check_tamper_back_event_callback(void* context) {
    furi_assert(context);
    CheckTamper* check_tamper = context;
    return scene_manager_handle_back_event(check_tamper->scene_manager);
}

void check_tamper_blink_read_start(CheckTamper* check_tamper) {
    notification_message(check_tamper->notifications, &sequence_blink_start_cyan);
}

void check_tamper_blink_stop(CheckTamper* check_tamper) {
    notification_message(check_tamper->notifications, &sequence_blink_stop);
}

static void check_tamper_rpc_command_callback(RpcAppSystemEvent event, void* context) {
    furi_assert(context);
    CheckTamper* check_tamper = context;

    furi_assert(check_tamper->rpc_ctx);

    if(event == RpcAppEventSessionClose) {
        view_dispatcher_send_custom_event(
            check_tamper->view_dispatcher, NfcCustomEventRpcSessionClose);
        rpc_system_app_set_callback(check_tamper->rpc_ctx, NULL, NULL);
        check_tamper->rpc_ctx = NULL;
    } else if(event == RpcAppEventAppExit) {
        view_dispatcher_send_custom_event(check_tamper->view_dispatcher, NfcCustomEventViewExit);
    } else if(event == RpcAppEventLoadFile) {
        view_dispatcher_send_custom_event(check_tamper->view_dispatcher, NfcCustomEventRpcLoad);
    } else {
        rpc_system_app_confirm(check_tamper->rpc_ctx, event, false);
    }
}

CheckTamper* check_tamper_alloc() {
    CheckTamper* check_tamper = malloc(sizeof(check_tamper));

    check_tamper->worker = nfc_worker_alloc();
    check_tamper->view_dispatcher = view_dispatcher_alloc();
    check_tamper->scene_manager = scene_manager_alloc(&check_tamper_scene_handlers, check_tamper);
    view_dispatcher_enable_queue(check_tamper->view_dispatcher);
    view_dispatcher_set_event_callback_context(check_tamper->view_dispatcher, check_tamper);
    view_dispatcher_set_custom_event_callback(
        check_tamper->view_dispatcher, check_tamper_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        check_tamper->view_dispatcher, check_tamper_back_event_callback);

    // Nfc device
    check_tamper->dev = nfc_device_alloc();
    furi_string_set(check_tamper->dev->folder, NFC_APP_FOLDER);

    // Open GUI record
    check_tamper->gui = furi_record_open(RECORD_GUI);

    // Open Notification record
    check_tamper->notifications = furi_record_open(RECORD_NOTIFICATION);

    // Submenu
    check_tamper->submenu = submenu_alloc();
    view_dispatcher_add_view(
        check_tamper->view_dispatcher,
        CheckTamperViewMenu,
        submenu_get_view(check_tamper->submenu));

    // Dialog
    check_tamper->dialog_ex = dialog_ex_alloc();
    view_dispatcher_add_view(
        check_tamper->view_dispatcher,
        CheckTamperViewDialogEx,
        dialog_ex_get_view(check_tamper->dialog_ex));

    // Popup
    check_tamper->popup = popup_alloc();
    view_dispatcher_add_view(
        check_tamper->view_dispatcher, CheckTamperViewPopup, popup_get_view(check_tamper->popup));

    // Generator
    check_tamper->generator = NULL;

    return check_tamper;
}

void check_tamper_free(CheckTamper* check_tamper) {
    furi_assert(check_tamper);

    if(check_tamper->rpc_state == CheckTamperRpcStateEmulating) {
        // Stop worker
        nfc_worker_stop(check_tamper->worker);
    } else if(check_tamper->rpc_state == CheckTamperRpcStateEmulated) {
        // Stop worker
        nfc_worker_stop(check_tamper->worker);
        // Save data in shadow file
        if(furi_string_size(check_tamper->dev->load_path)) {
            nfc_device_save_shadow(
                check_tamper->dev, furi_string_get_cstr(check_tamper->dev->load_path));
        }
    }

    if(check_tamper->rpc_ctx) {
        rpc_system_app_send_exited(check_tamper->rpc_ctx);
        rpc_system_app_set_callback(check_tamper->rpc_ctx, NULL, NULL);
        check_tamper->rpc_ctx = NULL;
    }

    // Nfc device
    nfc_device_free(check_tamper->dev);

    // Submenu
    view_dispatcher_remove_view(check_tamper->view_dispatcher, CheckTamperViewMenu);
    submenu_free(check_tamper->submenu);

    // DialogEx
    view_dispatcher_remove_view(check_tamper->view_dispatcher, CheckTamperViewDialogEx);
    dialog_ex_free(check_tamper->dialog_ex);

    // Popup
    view_dispatcher_remove_view(check_tamper->view_dispatcher, CheckTamperViewPopup);
    popup_free(check_tamper->popup);

    // Worker
    nfc_worker_stop(check_tamper->worker);
    nfc_worker_free(check_tamper->worker);

    // View Dispatcher
    view_dispatcher_free(check_tamper->view_dispatcher);

    // Scene Manager
    scene_manager_free(check_tamper->scene_manager);

    // GUI
    furi_record_close(RECORD_GUI);
    check_tamper->gui = NULL;

    // Notifications
    furi_record_close(RECORD_NOTIFICATION);
    check_tamper->notifications = NULL;

    free(check_tamper);
}

static bool nfc_is_hal_ready() {
    if(!furi_hal_nfc_is_init()) {
        // No connection to the chip, show an error screen
        DialogsApp* dialogs = furi_record_open(RECORD_DIALOGS);
        DialogMessage* message = dialog_message_alloc();
        dialog_message_set_text(
            message,
            "Error!\nNFC chip failed to start\n\n\nSend a photo of this to:\nsupport@flipperzero.one",
            0,
            0,
            AlignLeft,
            AlignTop);
        dialog_message_show(dialogs, message);
        dialog_message_free(message);
        furi_record_close(RECORD_DIALOGS);
        return false;
    } else {
        return true;
    }
}

int32_t check_tamper_app(void* p) {
    if(!nfc_is_hal_ready()) return 0;

    CheckTamper* check_tamper = check_tamper_alloc();

    FURI_LOG_E(TAG, "Start debugging");

    view_dispatcher_attach_to_gui(
        check_tamper->view_dispatcher, check_tamper->gui, ViewDispatcherTypeFullscreen);
    FURI_LOG_E(TAG, "1");
    scene_manager_next_scene(check_tamper->scene_manager, check_tamperSceneStart);
    FURI_LOG_E(TAG, "2");
    view_dispatcher_run(check_tamper->view_dispatcher);
    FURI_LOG_E(TAG, "3");

    check_tamper_free(check_tamper);

    return 0;
}
